# Generated by Django 3.0.6 on 2020-05-21 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogaplication',
            name='date',
        ),
        migrations.AddField(
            model_name='blogaplication',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogaplication',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogaplication',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogaplication',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
