# Generated by Django 3.0.6 on 2020-05-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogaplication_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogaplication',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
