# Generated by Django 3.0.6 on 2020-05-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200521_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogaplication',
            name='description',
            field=models.TextField(),
        ),
    ]
