# Generated by Django 3.0.6 on 2020-05-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200521_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogAplication',
            new_name='Post',
        ),
    ]
