# Generated by Django 3.0.6 on 2020-05-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200523_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='BlogAplication',
        ),
    ]
