# Generated by Django 3.0.6 on 2020-05-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200521_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
